### ISSUE TITLE
Check in on user if password has not been used after 2 days

### ISSUE THREAD

**Issue by nimra98** [lennart-perrey/Desive2#146]
If the user has not logged in until 2 days after the password mail has been sent, ask via mail if everything is alright.

**Comment by mariahenkel** [comment]
@nimra98 Isn't this the same as #40 (Check Login activity)?

**Comment by nimra98** [comment]
Depends.
Are we only checking for a first login or also for a login after a general password reset?

**Comment by mariahenkel** [comment]
Both refer to users who never used the app. Everything else is handled by general inactivity (push) notifications.

**Comment by nimra98** [comment]
@mariahenkel  It could refer to a user, who has reset his password and not logged in after this change. In this case, we do not have an ID to send the push notification to und must use emails.

**Comment by mariahenkel** [comment]
Should I add another mail-template for this?

**Comment by nimra98** [comment]
not doing this
