### ISSUE TITLE
New footer in Anmeldeformular looks out of place

### ISSUE THREAD

**Issue by mariahenkel** [lennart-perrey/Desive2#229]

**Comment by nimra98** [comment]
@mariahenkel Fix in html files. I want to make them modular in the 
future (as with the emails), but for now change the following files:

  * https://github.com/lennart-perrey/Desive2/blob/f46e879371c3bda331722f478755bd10374db078/API/Endpoint/private/resources/registerForm.html#L196
  * https://github.com/lennart-perrey/Desive2/blob/f46e879371c3bda331722f478755bd10374db078/API/Endpoint/private/resources/registerFailure.html#L192
  * https://github.com/lennart-perrey/Desive2/blob/f46e879371c3bda331722f478755bd10374db078/API/Endpoint/private/resources/registerSuccess.html#L197
  * https://github.com/lennart-perrey/Desive2/blob/f46e879371c3bda331722f478755bd10374db078/API/Endpoint/private/resources/resetPasswordFailure.html#L196
  * https://github.com/lennart-perrey/Desive2/blob/f46e879371c3bda331722f478755bd10374db078/API/Endpoint/private/resources/resetPasswordForm.html#L175
  * https://github.com/lennart-perrey/Desive2/blob/f46e879371c3bda331722f478755bd10374db078/API/Endpoint/private/resources/resetPasswordSuccess.html#L199

and use the same (or barely modified (e.g. delete the last sentence)) 
footer from here:

  * https://github.com/lennart-perrey/Desive2/blob/f46e879371c3bda331722f478755bd10374db078/API/Endpoint/private/resources/mail-templates/email-footer.html

Am 15.02.2023 um 11:09 schrieb Maria:

**Comment by mariahenkel** [comment]
Go away!

**Comment by mariahenkel** [comment]
@lennart-perrey please merge asap, branch includes updates due to data privacy regulations—thanks!
