### ISSUE TITLE
End of App Survey

### ISSUE THREAD

**Issue by lennart-perrey** [lennart-perrey/Desive2#35]
When Projects terminates, app has to show a popup, that it can be safely deleted

**Comment by nimra98** [comment]
Should the message be sent before or after incentive payout? (Ref #25)
Before would mean that any communication with the user must happen via e-mail.
After would mean that you have an app on your phone just for one or two push-notifications over the next 2 months or so.

**Comment by lennart-perrey** [comment]
ref #190
