### ISSUE TITLE
Check Login activity

### ISSUE THREAD

**Issue by lennart-perrey** [lennart-perrey/Desive2#40]
User needs to receive an email, when they have not used the app whithin 10 days

**Comment by nimra98** [comment]
[ ] Go down to 7 days
[ ] add column to AppUser "generated_on" for timestamp

**Comment by nimra98** [comment]
Dependent on #168

**Comment by nimra98** [comment]
@mariahenkel Pls add text to mail-template "API\Endpoint\private\resources\mail-templates\email-body-no-usage-reminder.html" on Branch "nimra98/issue40" (same syntax as the other files in this folder).

Is this e-mail an one-time event or should it be re-sent after time x?

**Comment by mariahenkel** [comment]
@nimra98 again after another 7 days, up to 3 times
