### ISSUE TITLE
Improve error handling in setPassword

### ISSUE THREAD

**Issue by nimra98** [lennart-perrey/Desive2#47]
If the OAuth fails, an error messages should get echoed.
This error messages should get interpreted correctly by the app (e.g. repeating the sending or the input process).

Referencing #22 

https://github.com/lennart-perrey/Desive2/blob/52ca2a59713238f01e7ab6d52d5ef2e68c9060d1/API/Endpoint/public/DBConnect.php#L85

**Comment by nimra98** [comment]
@lennart-perrey TODO: add in-app interpretation of error message. Would it make sense to specify the kind of error? (missing parameters vs. invalid token?)

**Comment by lennart-perrey** [comment]
ref #22

**Comment by lennart-perrey** [comment]
ref #72
