### ISSUE TITLE
API function: Provide the number of the last survey for a user

### ISSUE THREAD

**Issue by nimra98** [lennart-perrey/Desive2#69]
Provide the number of the last survey for a user
Answers:
If no S has been answered, echo "0"
If S1 has been answered, echo "1"
If S2 has been answered, echo "2"
If S3 has been answered, echo "3"

The app will always check against the first_login to see, if a new S is open for a user.
If "0", start first survey immediately.
If "1", check if today is first_login + 4 weeks.
If "2", check if today is first_login + 8 weeks.
If the API answers 3, the app will show the surveys as completed.

**Comment by nimra98** [comment]
Please use JSON Arrays!
The API could answer with an array of surveys and if they have been filled out by the user and when (...).

**Comment by lennart-perrey** [comment]
JSON Array should take the following form: 
array => (
survey1 => bool,
survey2 => bool,
survey3 => bool,
survey4 => bool)

API sided, an evaluation takes place, if a survey is oben for answering and provide a corresponding boolean value.
App sided, the OnAppearing() function should evaluate, if the corresponding view can be opened.

**Comment by nimra98** [comment]
Use getOpenSurveys as name for POST Call
